modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT License"

[[mods]]
modId = "cloudlib"
version = "${version}"
displayName = "ModPack Helper"
description = '''
Some useful features for minecraft modpack players.
'''
authors = "vfyjxf_"

[[dependencies.cloudlib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cloudlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.cloudlib]]
modId = "jei"
mandatory = true
versionRange = "[15.2.0.27,)"
ordering = "AFTER"
side = "BOTH"
