modLoader = "kotlinforforge"
loaderVersion = "${loader_version_range}"
license = "MIT License"

[[mixins]]
config="${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
    A lib mod.
'''
authors = "vfyjxf_"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange="${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId = "jei"
type="after"
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"