package dev.vfyjxf.cloudlib.gradle.lang;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Writes the merged chunks of one locale as a vanilla lang json file. JSON has no
 * comments, so the file is annotated with reserved magic keys (prefix {@code #}, which can
 * never collide with real translation keys since {@code #} starts a yaml comment): a
 * {@code #} header documenting the file and one {@code #<chunk>} separator before each
 * block of entries, naming the source yaml files the block was merged from.
 */
final class LangJsonWriter {

    private static final String COMMENT_KEY = "#";

    private LangJsonWriter() {
    }

    static String write(LangMerger.LocaleContent content) {
        List<String> lines = new ArrayList<>();
        lines.add(line(COMMENT_KEY, "Generated by the cloudLang gradle plugin from the distributed yaml lang files. Do not edit."));
        Set<String> seen = new HashSet<>();
        for (var chunk : content.chunks().entrySet()) {
            if (chunk.getValue().entries().isEmpty()) {
                continue;
            }
            lines.add(line(COMMENT_KEY + chunk.getKey(), "---- " + chunk.getKey() + " (" + String.join(", ", chunk.getValue().sources()) + ") ----"));
            for (var entry : chunk.getValue().entries().entrySet()) {
                if (!seen.add(entry.getKey())) {
                    throw new IllegalStateException("Duplicate lang key '" + entry.getKey() + "' in chunk '" + chunk.getKey()
                            + "': the same key is already provided by another file of this locale");
                }
                lines.add(line(entry.getKey(), entry.getValue()));
            }
        }
        return "{\n  " + String.join(",\n  ", lines) + "\n}\n";
    }

    private static String line(String key, String value) {
        return "\"" + escape(key) + "\": \"" + escape(value) + "\"";
    }

    private static String escape(String value) {
        StringBuilder out = new StringBuilder(value.length());
        for (char c : value.toCharArray()) {
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (c < 0x20) {
                        out.append(String.format("\\u%04x", (int) c));
                    } else {
                        out.append(c);
                    }
                }
            }
        }
        return out.toString();
    }

}
