package dev.vfyjxf.cloudlib.gradle.lang;

import java.util.Map;
import java.util.TreeMap;

/**
 * Writes the "R-like" key class. Keys carrying the {@code <modId>.} prefix are exposed as
 * {@code LangEntry} constants (never raw strings) grouped into nested classes that mirror
 * the dotted key structure; other keys (e.g. {@code item.<modId>.x} description ids coming
 * from datagen) are only packed into the json resources, not referenced from the class.
 *
 * <p>Constant names are derived from the key segments with the configured
 * {@link LangNameStyle}, unless the entry declares an explicit name via the annotated leaf
 * form ({@code $field:} in the yaml, see {@link LangMerger}).
 */
final class LangKeysClassWriter {

    private static final String GENERATOR_ID = "cloudLang gradle plugin";

    private LangKeysClassWriter() {
    }

    static String write(
            String packageName,
            String className,
            String entryClass,
            String generatedAnnotation,
            String modId,
            Map<String, String> entries,
            Map<String, String> fieldNames,
            LangNameStyle style
    ) {
        Node root = new Node();
        String prefix = modId + ".";
        for (var entry : entries.entrySet()) {
            String key = entry.getKey();
            if (!key.startsWith(prefix)) {
                continue;
            }
            root.add(key.substring(prefix.length()).split("\\."), key, entry.getValue());
        }

        String entrySimpleName = simpleName(entryClass);
        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");

        boolean imported = false;
        String annotationSimpleName = null;
        if (generatedAnnotation != null && !generatedAnnotation.isBlank()) {
            annotationSimpleName = simpleName(generatedAnnotation);
            imported |= appendImport(out, generatedAnnotation, annotationSimpleName, packageName);
        }
        imported |= appendImport(out, entryClass, entrySimpleName, packageName);
        if (imported) {
            out.append('\n');
        }

        out.append("/**\n");
        out.append(" * Generated by the cloudLang gradle plugin from the distributed yaml lang files. Do not edit.\n");
        out.append(" *\n");
        out.append(" * <p>Each constant mirrors one translation key of the {@code ").append(modId).append("} namespace.\n");
        out.append(" */\n");
        if (annotationSimpleName != null) {
            out.append('@').append(annotationSimpleName).append("(\"").append(GENERATOR_ID).append("\")\n");
        }
        out.append("public final class ").append(className).append(" {\n\n");
        out.append("    private ").append(className).append("() {\n");
        out.append("    }\n");
        writeNode(root, out, entrySimpleName, 1, fieldNames, style);
        out.append("}\n");
        return out.toString();
    }

    private static boolean appendImport(StringBuilder out, String fqn, String simpleName, String packageName) {
        String entryPackage = fqn.length() > simpleName.length() ? fqn.substring(0, fqn.length() - simpleName.length() - 1) : "";
        if (entryPackage.equals(packageName)) {
            return false;
        }
        out.append("import ").append(fqn).append(";\n");
        return true;
    }

    private static String simpleName(String fqn) {
        return fqn.substring(fqn.lastIndexOf('.') + 1);
    }

    private static void writeNode(Node node, StringBuilder out, String entrySimpleName, int depth, Map<String, String> fieldNames, LangNameStyle style) {
        String indent = "    ".repeat(depth);
        Map<String, Leaf> fields = new TreeMap<>();
        for (var leaf : node.leaves.entrySet()) {
            String fullKey = leaf.getValue().key;
            String explicit = fieldNames.get(fullKey);
            String field;
            if (explicit != null) {
                if (!LangNameStyle.isValidFieldName(explicit)) {
                    throw new IllegalStateException("Explicit field name '" + explicit + "' for key '" + fullKey
                            + "' is not a valid java identifier (or is a keyword)");
                }
                field = explicit;
            } else {
                field = style.fieldName(leaf.getKey());
            }
            Leaf previous = fields.putIfAbsent(field, leaf.getValue());
            if (previous != null) {
                throw new IllegalStateException("Constant name '" + field + "' is produced by both '" + previous.key
                        + "' and '" + fullKey + "'; rename one of the keys, give one an explicit 'field' name or choose another constantNameStyle");
            }
        }
        for (var field : fields.entrySet()) {
            out.append('\n');
            out.append(indent).append("/** ").append(escapeJavadoc(field.getValue().defaultValue)).append(" */\n");
            out.append(indent).append("public static final ").append(entrySimpleName).append(' ')
               .append(field.getKey()).append(" = ").append(entrySimpleName)
               .append(".of(\"").append(escapeString(field.getValue().key)).append("\");\n");
        }
        for (var child : node.children.entrySet()) {
            out.append('\n');
            out.append(indent).append("public static final class ").append(style.className(child.getKey())).append(" {\n\n");
            out.append(indent).append("    private ").append(style.className(child.getKey())).append("() {\n");
            out.append(indent).append("    }\n");
            writeNode(child.getValue(), out, entrySimpleName, depth + 1, fieldNames, style);
            out.append(indent).append("}\n");
        }
    }

    private static String escapeJavadoc(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("*/", "*&#47;");
    }

    private static String escapeString(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static final class Leaf {
        final String key;
        final String defaultValue;

        Leaf(String key, String defaultValue) {
            this.key = key;
            this.defaultValue = defaultValue;
        }
    }

    private static final class Node {
        final Map<String, Leaf> leaves = new TreeMap<>();
        final Map<String, Node> children = new TreeMap<>();

        void add(String[] segments, String key, String value) {
            Node node = this;
            for (int i = 0; i < segments.length - 1; i++) {
                node = node.children.computeIfAbsent(segments[i], segment -> new Node());
            }
            node.leaves.put(segments[segments.length - 1], new Leaf(key, value));
        }
    }

}
