package dev.vfyjxf.cloudlib.gradle.lang;

import org.junit.jupiter.api.Test;

import java.util.Map;
import java.util.TreeMap;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LangJsonWriterTest {

    @Test
    void writesChunkedFileWithMagicCommentKeys() {
        var chunks = new TreeMap<String, LangMerger.Chunk>();
        chunks.put("keys", new LangMerger.Chunk(
                new TreeMap<>(Map.of("cloudlib.keys.debug", "Debug")),
                Map.of(),
                java.util.List.of("src/main/lang/en_us/keys.yaml")
        ));
        chunks.put("blocks", new LangMerger.Chunk(
                new TreeMap<>(Map.of("block.cloudlib.test_block", "Test Block")),
                Map.of(),
                java.util.List.of("build/generated/datagen/lang/en_us/blocks.yaml")
        ));
        var content = new LangMerger.LocaleContent(chunks);

        String json = LangJsonWriter.write(content);

        assertTrue(json.startsWith("{\n"));
        assertTrue(json.contains("\"#\": \"Generated by the cloudLang gradle plugin from the distributed yaml lang files. Do not edit.\","));
        assertTrue(json.contains("\"#keys\": \"---- keys (src/main/lang/en_us/keys.yaml) ----\","));
        assertTrue(json.contains("\"#blocks\": \"---- blocks (build/generated/datagen/lang/en_us/blocks.yaml) ----\","));
        assertTrue(json.contains("\"block.cloudlib.test_block\": \"Test Block\""));
        assertTrue(json.contains("\"cloudlib.keys.debug\": \"Debug\""));
        assertTrue(json.endsWith("}\n"));
    }

    @Test
    void escapesValues() {
        var chunks = new TreeMap<String, LangMerger.Chunk>();
        chunks.put("ui", new LangMerger.Chunk(
                new TreeMap<>(Map.of("a.b", "quote \" backslash \\ newline \n")),
                Map.of(),
                java.util.List.of("src/main/lang/en_us/ui.yaml")
        ));

        String json = LangJsonWriter.write(new LangMerger.LocaleContent(chunks));

        assertTrue(json.contains("\"a.b\": \"quote \\\" backslash \\\\ newline \\n\""));
    }

    @Test
    void rejectsKeysDuplicatedAcrossChunks() {
        var chunks = new TreeMap<String, LangMerger.Chunk>();
        chunks.put("a", new LangMerger.Chunk(new TreeMap<>(Map.of("cloudlib.dup", "One")), Map.of(), java.util.List.of("a.yaml")));
        chunks.put("b", new LangMerger.Chunk(new TreeMap<>(Map.of("cloudlib.dup", "Two")), Map.of(), java.util.List.of("b.yaml")));

        assertThrows(IllegalStateException.class, () -> LangJsonWriter.write(new LangMerger.LocaleContent(chunks)));
    }

}
