modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT License"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
    In-world UI implementation for CloudLib: face-mounted, floating, follow
    and inspect-mode panels with trace interaction.
'''
authors = "vfyjxf_"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "cloudlib"
type = "required"
versionRange = "[${cloudlib_version},)"
ordering = "AFTER"
side = "BOTH"
