package dev.vfyjxf.cloudlib.data.lang;

import java.util.Map;

/**
 * Writes the entries of one {@link LangFile} as a flat yaml document, one
 * {@code dotted.key: "value"} pair per line. Kept deliberately small so datagen does not
 * need a yaml library on the classpath; hand-written files may still use nested mappings,
 * the gradle plugin flattens both forms identically.
 */
final class LangYamlWriter {

    private LangYamlWriter() {
    }

    static byte[] write(Map<String, String> entries) {
        StringBuilder out = new StringBuilder();
        out.append("# Generated by CloudLib datagen. Merged over src/main/lang at build time.\n");
        for (var entry : entries.entrySet()) {
            out.append(key(entry.getKey())).append(": \"").append(escape(entry.getValue())).append("\"\n");
        }
        return out.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
    }

    private static String key(String key) {
        for (char c : key.toCharArray()) {
            if (!Character.isLetterOrDigit(c) && c != '.' && c != '_' && c != '-') {
                return '"' + escape(key) + '"';
            }
        }
        return key;
    }

    private static String escape(String value) {
        StringBuilder out = new StringBuilder(value.length());
        for (char c : value.toCharArray()) {
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> out.append(c);
            }
        }
        return out.toString();
    }

}
